{
  "openapi": "3.0.0",
  "info": {
    "title": "API de cadastramento de Contas/Endereços",
    "description": "Essa API tem como objetivo possibilitar um CRUD de cadastramento de contas e endereços",
    "contact": {
      "email": "medradoogabriel@gmail.com",
      "telefone": "(11) 97577-3600"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "API Local"
    }
  ],
  "paths": {
    "/address/create": {
      "post": {
        "summary": "Cadastro de endereço",
        "description": "Esta rota será responsável por cadastrar um novo endereço.",
        "tags": ["Address"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Address"
              },
              "examples": {
                "address": {
                  "value": {
                    "logradouro": "Rua Tantas Palavras",
                    "numero": 777,
                    "complemento": "Bloco B apartamento 7",
                    "cidade": "São Paulo",
                    "estado": "São Paulo",
                    "cep": "08223-510"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad request"
          },
          "201": {
            "description": "Ok - Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Address"
                }
              }
            }
          }
        }
      }
    },
    "/address/list": {
      "get": {
        "description": "Listar endereços cadastrados.",
        "summary": "Responsável por listar os endereços cadastrados",
        "tags": ["Address"],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Address"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/address/delete/{id}": {
      "delete": {
        "summary": "Deleção de endereço",
        "description": "Esta rota será responsável por realizar a excluisão de endereços.",
        "tags": ["Address"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "description": "Id do endereço para exclusão.",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Ok - no content"
          },
          "400": {
            "description": "Solicitação invalida"
          }
        }
      }
    },
    "/address/atualizar/{id}": {
      "put": {
        "summary": "Atualizar um endereço",
        "description": "Esta rota será responsável por atualizar qualquer propriedade do endereço.",
        "tags": ["Address"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do endereço para atualização.",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Address"
              },
              "examples": {
                "address": {
                  "value": {
                    "logradouro": "Rua Parioto",
                    "numero": 137,
                    "complemento": "Bloco H apartamento 01",
                    "cidade": "Salvador",
                    "estado": "Bahia",
                    "cep": "07753-210"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok - Endereço atualizado com sucesso !",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Address"
                },
                "404": {
                  "description": "Id não encontrado"
                }
              }
            }
          }
        }
      }
    },
    "/client/create": {
      "post": {
        "summary": "Cadastro de cliente",
        "description": "Esta rota será responsável por cadastrar um novo cliente.",
        "tags": ["Client"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Client"
              },
              "examples": {
                "address": {
                  "value": {
                    "cnpj": "77521208000180",
                    "razao_social": "Medrados Company",
                    "nome_do_contato": "Gabriel Developer",
                    "telefone": 40028922
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Bad request"
          },
          "201": {
            "description": "Ok - Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Client"
                }
              }
            }
          }
        }
      }
    },
    "/client/list": {
      "get": {
        "description": "Listar clientes cadastrados.",
        "summary": "Responsável por listar os clientes cadastrados",
        "tags": ["Client"],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Client"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/client/delete/{id}": {
      "delete": {
        "summary": "Deleção de cliente",
        "description": "Esta rota será responsável por realizar a excluisão de clientes.",
        "tags": ["Client"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do cliente para exclusão.",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Ok - no content"
          },
          "400": {
            "description": "Solicitação invalida"
          }
        }
      }
    },
    "/client/atualizar/{id}": {
      "put": {
        "summary": "Atualizar um cliente",
        "description": "Esta rota será responsável por atualizar qualquer propriedade do cliente.",
        "tags": ["Client"],
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "Id do cliente para atualização.",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Client"
              },
              "examples": {
                "address": {
                  "value": {
                    "cnpj": "77521208000180",
                    "razao_social": "Medrados Company",
                    "nome_do_contato": "Gabriel Developer",
                    "telefone": 40028922
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok - Cliente atualizado com sucesso !",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Client"
                },
                "404": {
                  "description": "Id não encontrado"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Address": {
        "type": "object",
        "properties": {
          "logradouro": {
            "type": "string"
          },
          "numero": {
            "type": "number"
          },
          "complemento": {
            "type": "string",
            "required": false
          },
          "cidade": {
            "type": "string"
          },
          "estado": {
            "type": "string"
          },
          "cep": {
            "type": "string"
          }
        }
      },
      "Client": {
        "type": "object",
        "properties": {
          "cnpj": {
            "type": "string"
          },
          "razao_social": {
            "type": "string"
          },
          "nome_do_contato": {
            "type": "string"
          },
          "telefone": {
            "type": "number"
          }
        }
      }
    }
  }
}
